In [6]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


1.5.1
False


In [2]:
import numpy as np

In [4]:
lst = [1,2,3,4,5]
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.dtype

dtype('int64')

convert Numpy to Pytorch Tensors

In [7]:
tensors = torch.from_numpy(arr)
tensors

tensor([1, 2, 3, 4, 5])

In [9]:
type(tensors)

torch.Tensor

In [18]:
# indexing in tensors
tensors[:2]


tensor([1, 2])

In [17]:
tensors[4]

tensor(5)

In [21]:
# disadvantages of from_numpy: it will change both numpy array and torch array
tensors[4] = 100

In [22]:
tensors

tensor([  1,   2,   3,   4, 100])

In [23]:
arr

array([  1,   2,   3,   4, 100])

In [24]:
torch_arr = torch.tensor(arr)
torch_arr

tensor([  1,   2,   3,   4, 100])

In [25]:
torch_arr[0] = 200

In [26]:
torch_arr

tensor([200,   2,   3,   4, 100])

In [27]:
arr

array([  1,   2,   3,   4, 100])

In [30]:
# zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [31]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Airtmetic operations

In [40]:
a = torch.tensor(np.arange(0,20).reshape(5,4))
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [53]:
a[3:, 2:3]

tensor([[14],
        [18]])

In [55]:
#Airthmetic Operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [56]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [57]:
### tensor[7,9,15]
torch.add(a,b).sum()

tensor(27.)

In [58]:
# Dot Products and Mult Operations
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [59]:
x.mul(y)

tensor([12., 20., 30.])

In [60]:
### 3*4+5*4+6*5
x.dot(y)

tensor(62.)

In [61]:
###### MAtrix Multiplication
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [62]:
#All the below multiple operation do same thing
torch.matmul(x,y)
torch.mm(x,y)
x@y

tensor([[55., 53.],
        [90., 92.]])